name: Weekly Auto PR from Dev to Staging

on:
  # schedule:
  #   - cron: "0 13 * * 5"  # Runs every Friday at 8:00 AM EST (13:00 UTC)
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    permissions:
     contents: write  # To allow pushing changes to the repo
     pull-requests: write  # To create and manage pull requests
    steps:
      - uses: actions/checkout@v4
        with:
          ref: staging
      - name: Reset promotion branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: test/stage
